kind: Service
apiVersion: v1
metadata:
  labels:
    app: php-app
  name: php-app
  namespace: demo-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: php-app
